### ISSUE TITLE
unable to start cvu, SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by JunhongYu** [aestrivex/cvu#10]
hi there,

I got the following error when I tried to start CVU. I've installed all the dependencies except freesurfer

Traceback (most recent call last):
  File "/usr/local/bin/cvu", line 4, in <module>
    __import__('pkg_resources').run_script('cvu==0.5.2', 'cvu')
  File "/home/junhong/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/junhong/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1462, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/cvu-0.5.2-py2.7.egg/EGG-INFO/scripts/cvu", line 33, in <module>
    from cvu.main import main
  File "/usr/local/lib/python2.7/dist-packages/cvu-0.5.2-py2.7.egg/cvu/__init__.py", line 20, in <module>
    from .main import load_adj, load_parc, usage, main
  File "/usr/local/lib/python2.7/dist-packages/cvu-0.5.2-py2.7.egg/cvu/main.py", line 20, in <module>
    from gui import CvuGUI,ErrorHandler
  File "/usr/local/lib/python2.7/dist-packages/cvu-0.5.2-py2.7.egg/cvu/gui.py", line 24, in <module>
    from dataset import Dataset
  File "/usr/local/lib/python2.7/dist-packages/cvu-0.5.2-py2.7.egg/cvu/dataset.py", line 26, in <module>
    from dataview import (DataView,DVMayavi,DVMatrix,DVCircle)
  File "/usr/local/lib/python2.7/dist-packages/cvu-0.5.2-py2.7.egg/cvu/dataview.py", line 32, in <module>
    import circle_plot
  File "/usr/local/lib/python2.7/dist-packages/cvu-0.5.2-py2.7.egg/cvu/circle_plot.py", line 25, in <module>
    from mne.fixes import tril_indices
  File "/usr/local/lib/python2.7/dist-packages/mne/__init__.py", line 22, in <module>
    from .utils import (set_log_level, set_log_file, verbose, set_config,
  File "/usr/local/lib/python2.7/dist-packages/mne/utils/__init__.py", line 19, in <module>
    from .config import (set_config, get_config, get_config_path, set_cache_dir,
  File "/usr/local/lib/python2.7/dist-packages/mne/utils/config.py", line 539
    print(out, end='', file=fid)
                  ^
SyntaxError: invalid syntax

**Comment by aestrivex** [comment]
mne-python terminated support for python-2.7. I will plan to migrate the
project at some indefinite point in the future, but in the meantime you can
use older versions of mne-python which still support 2.7
