### ISSUE TITLE
Buttons on cvu  

### ISSUE THREAD

**Issue by Chux45** [aestrivex/cvu#7]
Hello,

I have managed to get cvu up and running on ubuntu .

> > > when I click the Load parcellation button i get the following error:

**Exception occurred in traits notification handler for object: <cvu.gui.CvuGUI object at 0x7fe696086050>, trait: load_parcellation_button, old value: <undefined>, new value: 0
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/traits-4.5.0-py2.7-linux-x86_64.egg/traits/trait_notifiers.py", line 340, in **call**
    self.handler( *args )
  File "/usr/local/lib/python2.7/dist-packages/cvu-0.5.2-py2.7.egg/cvu/gui.py", line 245, in _load_parcellation_button_fired
    self.parcellation_chooser_window.edit_traits()
  File "/usr/local/lib/python2.7/dist-packages/traitsui-5.1.0-py2.7.egg/traitsui/handler.py", line 445, in edit_traits
    self.trait_view_elements(), handler, id, scrollable, args )
  File "/usr/local/lib/python2.7/dist-packages/traitsui-5.1.0-py2.7.egg/traitsui/view.py", line 433, in ui
    ui.ui( parent, kind )
  File "/usr/local/lib/python2.7/dist-packages/traitsui-5.1.0-py2.7.egg/traitsui/ui.py", line 221, in ui
    self.rebuild( self, parent )
  File "/usr/local/lib/python2.7/dist-packages/traitsui-5.1.0-py2.7.egg/traitsui/wx/toolkit.py", line 140, in ui_live
    ui_live.ui_live( ui, parent )
  File "/usr/local/lib/python2.7/dist-packages/traitsui-5.1.0-py2.7.egg/traitsui/wx/ui_live.py", line 68, in ui_live
    ui_dialog( ui, parent, NONMODAL )
  File "/usr/local/lib/python2.7/dist-packages/traitsui-5.1.0-py2.7.egg/traitsui/wx/ui_live.py", line 99, in ui_dialog
    ui.owner.init( ui, parent, style )
  File "/usr/local/lib/python2.7/dist-packages/traitsui-5.1.0-py2.7.egg/traitsui/wx/ui_live.py", line 223, in init
    sw = panel( ui, window )
  File "/usr/local/lib/python2.7/dist-packages/traitsui-5.1.0-py2.7.egg/traitsui/wx/ui_panel.py", line 338, in panel
    content[0], ui )
  File "/usr/local/lib/python2.7/dist-packages/traitsui-5.1.0-py2.7.egg/traitsui/wx/ui_panel.py", line 512, in fill_panel_for_group
    create_panel )
  File "/usr/local/lib/python2.7/dist-packages/traitsui-5.1.0-py2.7.egg/traitsui/wx/ui_panel.py", line 659, in __init__
    self.add_groups( content, panel )
  File "/usr/local/lib/python2.7/dist-packages/traitsui-5.1.0-py2.7.egg/traitsui/wx/ui_panel.py", line 811, in add_groups
    fill_panel_for_group( panel, subgroup, self.ui )
  File "/usr/local/lib/python2.7/dist-packages/traitsui-5.1.0-py2.7.egg/traitsui/wx/ui_panel.py", line 512, in fill_panel_for_group
    create_panel )
  File "/usr/local/lib/python2.7/dist-packages/traitsui-5.1.0-py2.7.egg/traitsui/wx/ui_panel.py", line 661, in **init**
    self.add_items(content, panel, self.sizer)
  File "/usr/local/lib/python2.7/dist-packages/traitsui-5.1.0-py2.7.egg/traitsui/wx/ui_panel.py", line 1020, in add_items
    editor.prepare( item_panel )
  File "/usr/local/lib/python2.7/dist-packages/traitsui-5.1.0-py2.7.egg/traitsui/editor.py", line 158, in prepare
    self.update_editor()
  File "/usr/local/lib/python2.7/dist-packages/cvu-0.5.2-py2.7.egg/cvu/custom_file_editor.py", line 161, in update_editor
    set_text(self, self.value)
  File "/usr/local/lib/python2.7/dist-packages/cvu-0.5.2-py2.7.egg/cvu/custom_file_editor.py", line 110, in set_text
    if _tk == 'wx': return editor.text_control.SetValue(text)
AttributeError: 'NoneType' object has no attribute 'SetValue'
Exception occurred in traits notification handler for object: <cvu.gui.CvuGUI object at 0x7fe696086050>, trait: load_parcellation_button, old value: <undefined>, new value: 0
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/traits-4.5.0-py2.7-linux-x86_64.egg/traits/trait_notifiers.py", line 340, in __call__
    self.handler( *args )
  File "/usr/local/lib/python2.7/dist-packages/cvu-0.5.2-py2.7.egg/cvu/gui.py", line 245, in _load_parcellation_button_fired
    self.parcellation_chooser_window.edit_traits()
  File "/usr/local/lib/python2.7/dist-packages/traitsui-5.1.0-py2.7.egg/traitsui/handler.py", line 445, in edit_traits
    self.trait_view_elements(), handler, id, scrollable, args )
  File "/usr/local/lib/python2.7/dist-packages/traitsui-5.1.0-py2.7.egg/traitsui/view.py", line 433, in ui
    ui.ui( parent, kind )
  File "/usr/local/lib/python2.7/dist-packages/traitsui-5.1.0-py2.7.egg/traitsui/ui.py", line 221, in ui
    self.rebuild( self, parent )
  File "/usr/local/lib/python2.7/dist-packages/traitsui-5.1.0-py2.7.egg/traitsui/wx/toolkit.py", line 140, in ui_live
    ui_live.ui_live( ui, parent )
  File "/usr/local/lib/python2.7/dist-packages/traitsui-5.1.0-py2.7.egg/traitsui/wx/ui_live.py", line 68, in ui_live
    ui_dialog( ui, parent, NONMODAL )
  File "/usr/local/lib/python2.7/dist-packages/traitsui-5.1.0-py2.7.egg/traitsui/wx/ui_live.py", line 99, in ui_dialog
    ui.owner.init( ui, parent, style )
  File "/usr/local/lib/python2.7/dist-packages/traitsui-5.1.0-py2.7.egg/traitsui/wx/ui_live.py", line 223, in init
    sw = panel( ui, window )
  File "/usr/local/lib/python2.7/dist-packages/traitsui-5.1.0-py2.7.egg/traitsui/wx/ui_panel.py", line 338, in panel
    content[0], ui )
  File "/usr/local/lib/python2.7/dist-packages/traitsui-5.1.0-py2.7.egg/traitsui/wx/ui_panel.py", line 512, in fill_panel_for_group
    create_panel )
  File "/usr/local/lib/python2.7/dist-packages/traitsui-5.1.0-py2.7.egg/traitsui/wx/ui_panel.py", line 659, in __init__
    self.add_groups( content, panel )
  File "/usr/local/lib/python2.7/dist-packages/traitsui-5.1.0-py2.7.egg/traitsui/wx/ui_panel.py", line 811, in add_groups
    fill_panel_for_group( panel, subgroup, self.ui )
  File "/usr/local/lib/python2.7/dist-packages/traitsui-5.1.0-py2.7.egg/traitsui/wx/ui_panel.py", line 512, in fill_panel_for_group
    create_panel )
  File "/usr/local/lib/python2.7/dist-packages/traitsui-5.1.0-py2.7.egg/traitsui/wx/ui_panel.py", line 661, in **init**
    self.add_items(content, panel, self.sizer)
  File "/usr/local/lib/python2.7/dist-packages/traitsui-5.1.0-py2.7.egg/traitsui/wx/ui_panel.py", line 1020, in add_items
    editor.prepare( item_panel )
  File "/usr/local/lib/python2.7/dist-packages/traitsui-5.1.0-py2.7.egg/traitsui/editor.py", line 158, in prepare
    self.update_editor()
  File "/usr/local/lib/python2.7/dist-packages/cvu-0.5.2-py2.7.egg/cvu/custom_file_editor.py", line 161, in update_editor
    set_text(self, self.value)
  File "/usr/local/lib/python2.7/dist-packages/cvu-0.5.2-py2.7.egg/cvu/custom_file_editor.py", line 110, in set_text
    if _tk == 'wx': return editor.text_control.SetValue(text)
AttributeError: 'NoneType' object has no attribute 'SetValue'**

> > > > when I click the load an adjacency matrix button I get the following error:

**Exception occurred in traits notification handler for object: <cvu.gui.CvuGUI object at 0x7fe696086050>, trait: load_adjmat_button, old value: <undefined>, new value: 0
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/traits-4.5.0-py2.7-linux-x86_64.egg/traits/trait_notifiers.py", line 340, in **call**
    self.handler( *args )
  File "/usr/local/lib/python2.7/dist-packages/cvu-0.5.2-py2.7.egg/cvu/gui.py", line 288, in _load_adjmat_button_fired
    self.adjmat_chooser_window.edit_traits()
  File "/usr/local/lib/python2.7/dist-packages/traitsui-5.1.0-py2.7.egg/traitsui/handler.py", line 445, in edit_traits
    self.trait_view_elements(), handler, id, scrollable, args )
  File "/usr/local/lib/python2.7/dist-packages/traitsui-5.1.0-py2.7.egg/traitsui/view.py", line 433, in ui
    ui.ui( parent, kind )
  File "/usr/local/lib/python2.7/dist-packages/traitsui-5.1.0-py2.7.egg/traitsui/ui.py", line 221, in ui
    self.rebuild( self, parent )
  File "/usr/local/lib/python2.7/dist-packages/traitsui-5.1.0-py2.7.egg/traitsui/wx/toolkit.py", line 140, in ui_live
    ui_live.ui_live( ui, parent )
  File "/usr/local/lib/python2.7/dist-packages/traitsui-5.1.0-py2.7.egg/traitsui/wx/ui_live.py", line 68, in ui_live
    ui_dialog( ui, parent, NONMODAL )
  File "/usr/local/lib/python2.7/dist-packages/traitsui-5.1.0-py2.7.egg/traitsui/wx/ui_live.py", line 99, in ui_dialog
    ui.owner.init( ui, parent, style )
  File "/usr/local/lib/python2.7/dist-packages/traitsui-5.1.0-py2.7.egg/traitsui/wx/ui_live.py", line 223, in init
    sw = panel( ui, window )
  File "/usr/local/lib/python2.7/dist-packages/traitsui-5.1.0-py2.7.egg/traitsui/wx/ui_panel.py", line 350, in panel
    nb    = create_notebook_for_items( content, ui, parent, None )
  File "/usr/local/lib/python2.7/dist-packages/traitsui-5.1.0-py2.7.egg/traitsui/wx/ui_panel.py", line 391, in create_notebook_for_items
    is_dock_window = True )
  File "/usr/local/lib/python2.7/dist-packages/traitsui-5.1.0-py2.7.egg/traitsui/wx/ui_panel.py", line 512, in fill_panel_for_group
    create_panel )
  File "/usr/local/lib/python2.7/dist-packages/traitsui-5.1.0-py2.7.egg/traitsui/wx/ui_panel.py", line 661, in __init__
    self.add_items(content, panel, self.sizer)
  File "/usr/local/lib/python2.7/dist-packages/traitsui-5.1.0-py2.7.egg/traitsui/wx/ui_panel.py", line 1020, in add_items
    editor.prepare( item_panel )
  File "/usr/local/lib/python2.7/dist-packages/traitsui-5.1.0-py2.7.egg/traitsui/editor.py", line 158, in prepare
    self.update_editor()
  File "/usr/local/lib/python2.7/dist-packages/cvu-0.5.2-py2.7.egg/cvu/custom_file_editor.py", line 161, in update_editor
    set_text(self, self.value)
  File "/usr/local/lib/python2.7/dist-packages/cvu-0.5.2-py2.7.egg/cvu/custom_file_editor.py", line 110, in set_text
    if _tk == 'wx': return editor.text_control.SetValue(text)
AttributeError: 'NoneType' object has no attribute 'SetValue'**

> > > > > and also when I click on load tractography

**Exception occurred in traits notification handler for object: <cvu.gui.CvuGUI object at 0x7fe696086050>, trait: load_tractography_button, old value: <undefined>, new value: 0
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/traits-4.5.0-py2.7-linux-x86_64.egg/traits/trait_notifiers.py", line 340, in **call**
    self.handler( *args )
  File "/usr/local/lib/python2.7/dist-packages/cvu-0.5.2-py2.7.egg/cvu/gui.py", line 307, in _load_tractography_button_fired
    self.tractography_chooser_window.edit_traits()
  File "/usr/local/lib/python2.7/dist-packages/traitsui-5.1.0-py2.7.egg/traitsui/handler.py", line 445, in edit_traits
    self.trait_view_elements(), handler, id, scrollable, args )
  File "/usr/local/lib/python2.7/dist-packages/traitsui-5.1.0-py2.7.egg/traitsui/view.py", line 433, in ui
    ui.ui( parent, kind )
  File "/usr/local/lib/python2.7/dist-packages/traitsui-5.1.0-py2.7.egg/traitsui/ui.py", line 221, in ui
    self.rebuild( self, parent )
  File "/usr/local/lib/python2.7/dist-packages/traitsui-5.1.0-py2.7.egg/traitsui/wx/toolkit.py", line 140, in ui_live
    ui_live.ui_live( ui, parent )
  File "/usr/local/lib/python2.7/dist-packages/traitsui-5.1.0-py2.7.egg/traitsui/wx/ui_live.py", line 68, in ui_live
    ui_dialog( ui, parent, NONMODAL )
  File "/usr/local/lib/python2.7/dist-packages/traitsui-5.1.0-py2.7.egg/traitsui/wx/ui_live.py", line 99, in ui_dialog
    ui.owner.init( ui, parent, style )
  File "/usr/local/lib/python2.7/dist-packages/traitsui-5.1.0-py2.7.egg/traitsui/wx/ui_live.py", line 223, in init
    sw = panel( ui, window )
  File "/usr/local/lib/python2.7/dist-packages/traitsui-5.1.0-py2.7.egg/traitsui/wx/ui_panel.py", line 338, in panel
    content[0], ui )
  File "/usr/local/lib/python2.7/dist-packages/traitsui-5.1.0-py2.7.egg/traitsui/wx/ui_panel.py", line 512, in fill_panel_for_group
    create_panel )
  File "/usr/local/lib/python2.7/dist-packages/traitsui-5.1.0-py2.7.egg/traitsui/wx/ui_panel.py", line 659, in __init__
    self.add_groups( content, panel )
  File "/usr/local/lib/python2.7/dist-packages/traitsui-5.1.0-py2.7.egg/traitsui/wx/ui_panel.py", line 811, in add_groups
    fill_panel_for_group( panel, subgroup, self.ui )
  File "/usr/local/lib/python2.7/dist-packages/traitsui-5.1.0-py2.7.egg/traitsui/wx/ui_panel.py", line 512, in fill_panel_for_group
    create_panel )
  File "/usr/local/lib/python2.7/dist-packages/traitsui-5.1.0-py2.7.egg/traitsui/wx/ui_panel.py", line 661, in **init**
    self.add_items(content, panel, self.sizer)
  File "/usr/local/lib/python2.7/dist-packages/traitsui-5.1.0-py2.7.egg/traitsui/wx/ui_panel.py", line 1020, in add_items
    editor.prepare( item_panel )
  File "/usr/local/lib/python2.7/dist-packages/traitsui-5.1.0-py2.7.egg/traitsui/editor.py", line 158, in prepare
    self.update_editor()
  File "/usr/local/lib/python2.7/dist-packages/cvu-0.5.2-py2.7.egg/cvu/custom_file_editor.py", line 161, in update_editor
    set_text(self, self.value)
  File "/usr/local/lib/python2.7/dist-packages/cvu-0.5.2-py2.7.egg/cvu/custom_file_editor.py", line 110, in set_text
    if _tk == 'wx': return editor.text_control.SetValue(text)
AttributeError: 'NoneType' object has no attribute 'SetValue'**

Whats the best way to solve this?

Best,

Chux

**Comment by aestrivex** [comment]
You are still using the system python and it is defaulting to the wx
toolkit. I recommend to install a standalone anaconda distribution in your
home directory, and install the dependencies there.

**Comment by Chux45** [comment]
Thanks Aestrivex,
I  got cvu running in miniconda. 

> I downloaded miniconda for linux (http://conda.pydata.org/miniconda.html)
> created an isolated environment (http://conda.pydata.org/docs/using/envs.html)
> installed cvu dependencies 
> installed nipype as I think I may need this for freesurfer? ( conda config --add channels conda-forge _then_ conda install nipype)
> installed cvu via pip install cvu
> entered: export QT_API=pyside into terminal 
> entered: cvu in terminal and it started up

Buttons are all working.

Thanks Chux
