### ISSUE TITLE
Problem installed cvu in mac under Anaconda virtual environment

### ISSUE THREAD

**Issue by javiergcas** [aestrivex/cvu#8]
Hello,

I am trying to install CVU on a Mac. I use Anaconda with python 2.7 as my python. I create a python environment where I think I have installed all necessary packages. When I try to run cvu from a shell, I get the following error:

Traceback (most recent call last):
  File "/Users/javiergc/anaconda/envs/cvu/bin/cvu", line 33, in <module>
    from cvu.main import main
  File "/Users/javiergc/anaconda/envs/cvu/lib/python2.7/site-packages/cvu/__init__.py", line 20, in <module>
    from .main import load_adj, load_parc, usage, main
  File "/Users/javiergc/anaconda/envs/cvu/lib/python2.7/site-packages/cvu/main.py", line 20, in <module>
    from gui import CvuGUI,ErrorHandler
  File "/Users/javiergc/anaconda/envs/cvu/lib/python2.7/site-packages/cvu/gui.py", line 24, in <module>
    from dataset import Dataset
  File "/Users/javiergc/anaconda/envs/cvu/lib/python2.7/site-packages/cvu/dataset.py", line 24, in <module>
    from color_legend import (ColorLegend,LegendEntry)
  File "/Users/javiergc/anaconda/envs/cvu/lib/python2.7/site-packages/cvu/color_legend.py", line 40, in <module>
    class ColorLegendWindow(HasTraits):
  File "/Users/javiergc/anaconda/envs/cvu/lib/python2.7/site-packages/cvu/color_legend.py", line 48, in ColorLegendWindow
    selection_bg_color=None,),show_label=False),
  File "/Users/javiergc/anaconda/envs/cvu/lib/python2.7/site-packages/traitsui/editor_factory.py", line 94, in __init__
    HasPrivateTraits.__init__( self, **traits )
  File "/Users/javiergc/anaconda/envs/cvu/lib/python2.7/site-packages/traits/trait_handlers.py", line 172, in error
    value )
traits.trait_errors.TraitError: The 'selection_bg_color' trait of a ToolkitEditorFactory instance must be an integer which in hex is of the form 0xRRGGBB, where RR is red, GG is green, and BB is blue or 'aquamarine' or 'black' or 'blue violet' or 'blue' or 'brown' or 'cadet blue' or 'coral' or 'cornflower blue' or 'cyan' or 'dark green' or 'dark grey' or 'dark olive green' or 'dark orchid' or 'dark slate blue' or 'dark slate grey' or 'dark turquoise' or 'dim grey' or 'firebrick' or 'forest green' or 'gold' or 'goldenrod' or 'green yellow' or 'green' or 'grey' or 'indian red' or 'khaki' or 'light blue' or 'light grey' or 'light steel' or 'lime green' or 'magenta' or 'maroon' or 'medium aquamarine' or 'medium blue' or 'medium forest green' or 'medium goldenrod' or 'medium orchid' or 'medium sea green' or 'medium slate blue' or 'medium spring green' or 'medium turquoise' or 'medium violet red' or 'midnight blue' or 'navy' or 'orange red' or 'orange' or 'orchid' or 'pale green' or 'pink' or 'plum' or 'purple' or 'red' or 'salmon' or 'sea green' or 'sienna' or 'sky blue' or 'slate blue' or 'spring green' or 'steel blue' or 'tan' or 'thistle' or 'turquoise' or 'violet red' or 'violet' or 'wheat' or 'white' or 'yellow green' or 'yellow', but a value of None <type 'NoneType'> was specified.

Could you please let me know how to solve this issue. 

Thanks a lot,

Javier.

**Comment by aestrivex** [comment]
What version of traits are you using

**Comment by javiergcas** [comment]
The traits version is 4.6.0

Thanks

**Comment by Conxz** [comment]
I have the same problem. Any solutions?
